version: '3.8'

services:
  api:
    container_name: fake-robot-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure