version: '3.8'


services:
  api:
    env_file:
      - ./.env
    container_name: fake-robot-api
    build:
      context: .
      args:
        - PORT=5001
      dockerfile: Dockerfile
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"
    restart: on-failure